name: workflow_dist

on: [push,workflow_dispatch]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: "greet"
              run: echo "hello World!"
              

        

