name: workflow_dist

on:
    push:
       branches:
         - main
         - features
       paths-ignore:
         - '.github/workflows/**'
         - README.md

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "greet"
              run: echo "hello World!"
    clone-repo:
        runs-on: ubuntu-latest
        steps:
            - name: "clone repo"
              uses: actions/checkout@v4

            - name: "install node 20"
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Cache Dependencies
              uses: actions/cache@v4
              with:
               path: ~/.npm
               key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: "print node version"
              run: node -v
            - name: "install dependencies"
              run: npm ci
            - name: "run test"
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: "get code"
            uses: actions/checkout@v4

          - name: "install node"
            uses: actions/setup-node@v4
          - name: Cache Dependencies
            uses: actions/cache@v4
            with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          - name: "install dependencies"
            run: npm ci
          - name: "build the project"
            run: npm run build 

          - name: "deploy"
            run: echo "deploued successfully"

        
            
              

        

