name: workflow_dist

on: [push,workflow_dispatch]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: "greet"
              run: echo "hello World!"
    clone-repo:
        runs-on: ubuntu-latest
        steps:
            - name: "clone repo"
              uses: actions/checkout@v4
              

        

